@url = https://localhost:7241/api


# @name getCustomers
GET {{url}}/customers
###

# @name registerCustomer
POST {{url}}/customers/register
content-type: application/json

{
  "name": "Nguyen Van A",
  "password": "nguyenvana",
  "userName": "nguyenvanaa",
  "email": "admin@mail.com"
}
###

# @name getProducts
GET {{url}}/products 
###

# @name createProduct
POST {{url}}/products
content-type: application/json

{
  "name": "Macbook",
  "moneyValue": 100,
  "currency": "USA",
  "tradeMark": "Apple",
  "origin": "China",
  "discription": "This is a macbook."
}
###


@productId = 2

# @name updateProduct
PUT {{url}}/products/{{productId}}
Content-Type: application/json

{
  "name": "string",
  "price": {
    "value": 0,
    "currency": "string"
  },
  "tradeMark": "string",
  "origin": "string",
  "discription": "string"
}
###

# @name deleteProduct
DELETE {{url}}/products/{{productId}}
###

@cartId = 4
@customerId = {{registerCustomer.response.body.customerId}}

# @name getCartDetails
GET {{url}}/customers/{{customerId}}/cart?cartId={{cartId}}
Content-Type: application/json
###



# @name addProductToCart
POST {{url}}/customers/{{customerId}}/cart/products?cartId={{cartId}}
Content-Type: application/json

{
  "productId": 2,
  "quantity": 3
}
###

@cardProductId = 3

# @name changeProductQuantity
PUT {{url}}/customers/{{customerId}}/carts/{{cartId}}/products/{{cardProductId}}
Content-Type: application/json

{
  "productId": 3,
  "quantity": 5
}
###

# @name removeProductFromCart
DELETE {{url}}/customers/{{customerId}}/carts/{{cartId}}/products/{{cardProductId}}
###

# @name placeOrder
POST {{url}}/customers/{{customerId}}/cart/place-order?cartId={{cartId}}
Content-Type: application/json

{
}
###

# @name getallOrders
GET {{url}}/orders/get-all
###

# @name getOrdersbyId
GET {{url}}/orders?customerId={{customerId}}
###

@orderId = 2

# @name getOrderDetails
GET {{url}}/orders/{{orderId}}?customerId={{customerId}}
###

# @name changeOrderStatus
PUT {{url}}/orders/{{orderId}}/change-orderstatus
Content-Type: application/json

{
  "orderStatus": 2
}
####
