version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: Express
  testonlineproject.api:
    image: ${DOCKER_REGISTRY-}testonlineprojectapi
    container_name: testonlineprojectapi
    build:
      context: .
      dockerfile: TestOnlineProject.API/Dockerfile
    depends_on:
      - sqlserver