name: CI work flow

on:
  push:
    # paths:
    #   - 'src/**'
    #   - 'tests/**'
    # branches: [ dev ]
  pull_request:
    # branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/TestOnlineProject.API

    - name: Build
      run: dotnet build --no-restore
      working-directory: src/TestOnlineProject.API

    - name: Run unit tests
      run: dotnet test
      working-directory: tests/TestOnlineProject.Test

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        # registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        path: .
        dockerfile: 'src/docker-compose.dcproj'
        repository: 'getting-started'
        tags: 'linux-latest'
        push: true
